---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: Create certificate verify 
      fwebos_certificate_verify:
       action: add 
       vdom: root1
       name: test
       publish_dn: disable
       strictly_need_cert: enable
       ca: test1
       crl: 

    - name: edit certificate verify 
      fwebos_certificate_verify:
       action: edit 
       vdom: root1
       name: test
       publish_dn: disable
       strictly_need_cert: disable 
       ca: test1
       crl: 

    - name: delete certificate verify 
      fwebos_certificate_verify:
       action: delete 
       vdom: root1
       name: test 
 
