---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: deletet sni certificate group 
      fwebos_certificate_sni_group:
       action: delete 
       name: test1 
       vdom: root1
          
    - name: Create xml client certificate group 
      fwebos_certificate_sni_group:
       action: add 
       name: test1
       vdom: root1
