---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: revoke certificate letsencrypt
      fwebos_certificate_letsencrypt_revoke:
       action: revoke 
       vdom: root1
       name: test123
       domain: test123.com
