---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: delete urlcert certificate group 
      fwebos_certificate_urlcert_group:
       action: delete 
       name: test 
       vdom: root1
          
    - name: Create urlcert certificate group 
      fwebos_certificate_urlcert_group:
       action: add 
       name: test
       vdom: root1
