---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: Create certificate urlcert list
      fwebos_certificate_urlcert_list:
       action: add 
       vdom: root1 
       table_name: test1 
       url: test1.com
       require: enable

    - name: edit certificate urlcert list
      fwebos_certificate_urlcert_list:
       action: edit 
       vdom: root1
       table_name: test1 
       name: 1 
       url: test1.com
       require: enable

    - name: delete certificate urlcert list
      fwebos_certificate_urlcert_list:
       action: delete 
       vdom: root1
       table_name: test1 
       name: 1 
