---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: Create member
      fwebos_certificate_ca_group_member:
       action: add 
       vdom: root1 
       table_name: test 
       name: CA_Cert_1
       type: CA 
       publish_dn: enable

    - name: edit member
      fwebos_certificate_ca_group_member:
       action: edit 
       vdom: root1
       table_name: test 
       name: CA_Cert_1
       id: 1 
       type: CA
       publish_dn: disable 

    - name: delete member
      fwebos_certificate_ca_group_member:
       action: delete 
       vdom: root1
       table_name: test 
       id: 1 
