---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: delete offline sni certificate group 
      fwebos_certificate_offline_sni_group:
       action: delete 
       name: test2 
       vdom: root1
          
    - name: Create offline sni certificate group 
      fwebos_certificate_offline_sni_group:
       action: add 
       name: test2
       vdom: root1
