---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: issue certificate letsencrypt
      fwebos_certificate_letsencrypt_issue:
       action: issue 
       vdom: root1
       name: test123
       domain: test123.com
