---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:

    - name: add a ML Based API protection policy
      fwebos_ml_based_api_protection_policy:
        action: add 
        policy_id: 15296982069610136571
        rule_domain:
          - ddccd
          - aadddc
        rule_ip:
          - 1.2.3.4
          - 10.2.41.34

    - name: add a ML Based API protection policy domain
      fwebos_ml_based_api_protection_policy_domain:
        action: add 
        id: 1
        policy_id: 11987745072721173265
        domain_name: domain1

    - name: get all ML Based API protection policy domain
      fwebos_ml_based_api_protection_policy_domain:
        action: get 

    - name: get a ML Based API protection policy domain
      fwebos_ml_based_api_protection_policy_domain:
        action: get 
        domain_id: 1

    - name: retrain a ML Based API protection policy domain
      fwebos_ml_based_api_protection_policy_domain:
        action: retrain 
        domain_id: 1

    - name: delete a ML Based API protection policy domain
      fwebos_ml_based_api_protection_policy_domain:
        action: delete 
        domain_id: 1

    - name: delete a ML Based API protection policy domain again
      fwebos_ml_based_api_protection_policy_domain:
        action: delete 
        domain_id: 1

    - name: retrain a non-existant ML Based API protection policy domain
      fwebos_ml_based_api_protection_policy_domain:
        action: retrain 
        domain_id: 1

    - name: delete a ML Based API protection policy
      fwebos_ml_based_api_protection_policy:
        action: delete
        id: 1