---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: Create server
      fwebos_virtual_server:
       action: add
       name: test4
       vdom: root

    - name: Create vip
      fwebos_virtual_server_vip:
       action: add
       table_name: test4
       vip: test
       status: disable
       vdom: root

    - name: edit 
      fwebos_virtual_server_vip:
       action: edit 
       table_name: test4
       vip: test
       status: enable 
       name: 1 
       vdom: root

    - name: delete vip
      fwebos_virtual_server_vip:
       action: delete 
       table_name: test4
       name: 1 
       vdom: root

    - name: delete server
      fwebos_virtual_server:
       action: delete
       name: test4
       vdom: root
