---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: Create
      fwebos_server_service:
       action: add
       name: test1
       port: 331
       vdom: root

    - name: get
      fwebos_server_service:
       action: get
       name: test1

    - name: edit
      fwebos_server_service:
       action: edit
       name: test1
       port: 303
       vdom: root

    - name: delete
      fwebos_server_service:
       action: delete
       name: test1

