---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: Create
      fwebos_waf_xml_policy:
       action: add
       name: test4
       enable_signature_detection: disable
       vdom: root
