---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: Create
      fwebos_virtual_server_vip:
       action: add
       table_name: test4
       vip: test4
       vdom: root
