---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: Create
      fwebos_waf_http_constraints_exceptions:
       action: add
       name: test4
       vdom: root
