---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: delete 
      fwebos_waf_file_upload_policy:
       action: delete 
       name: aaa
       vdom: root
          
    - name: Create
      fwebos_waf_file_upload_policy:
       action: add
       vdom: root
       block_period: 600
       severity: Medium
       av_scan: disable
       icap_server_check: disable
       name: test4
       fortisandbox_check: disable
       exchange_mail_detection: disable
       file_action: alert
       hold_session_while_scanning_file: disable

    - name: edit
      fwebos_waf_file_upload_policy:
       action: edit 
       vdom: root
       block_period: 600
       severity: Medium
       av_scan: disable
       icap_server_check: disable
       name: test4
       fortisandbox_check: disable
       exchange_mail_detection: disable
       file_action: alert
       hold_session_while_scanning_file: disable
