---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: Create
      fwebos_waf_file_upload_policy_rule:
       action: add
       table_name: test4
       file_upload_restriction_rule: test4
       vdom: root
