---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: Create
      fwebos_waf_custom_protection_group_type_list:
       action: add
       table_name: test4
       custom_protection_rule: test4
       vdom: root
