---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: add a policy first
      fwebos_waf_http_header_security_policy_exception:
       action: add 
       name: e1

    - name: add a New Secure Header Exception Item
      fwebos_waf_http_header_security_policy_exception_item:
       action: add 
       name: e1
       client_ip_status: enable
       client_ip: 10.2.3.4-10.2.3.55
       request_url_type: plain
       request_url_pattern: /www.test.com

    - name: add a New Secure Header Exception Item
      fwebos_waf_http_header_security_policy_exception_item:
       action: add 
       name: e1
       request_url_pattern: /www.334455.com

    - name: edit a New Secure Header Exception Item
      fwebos_waf_http_header_security_policy_exception_item:
       action: edit 
       name: e1
       id: 1
       client_ip_status: enable
       client_ip: 10.2.3.4-10.2.3.55
       request_url_type: regular
       request_url_pattern: aa11bb

    - name: edit a New Secure Header Exception Item
      fwebos_waf_http_header_security_policy_exception_item:
       action: edit 
       name: e1
       id: 1
       client_ip_status: enable
       client_ip: 10.2.3.4-10.2.3.55
       request_url_type: regular
       request_url_pattern: aa11bb

    - name: delete a Secure Header Exception Item
      fwebos_waf_http_header_security_policy_exception_item:
       action: delete 
       name: e1
       id: 1

    - name: delete a Secure Header Exception Item again
      fwebos_waf_http_header_security_policy_exception_item:
       action: delete 
       name: e1
       id: 1

