---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: Add HSM server
      fwebos_hsm_server:
       action: add
       name: test4
       ip: 172.30.30.13
       timeout: 20000
       vdom: root
       srcfile: hsm7-server.pem

    - name: Delete HSM server
      fwebos_hsm_server:
       action: delete 
       vdom: root
       name: test
